spring.application.name=meenakshi

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_KEY}
cloudinary.api-secret=${CLOUDINARY_SECRET}

# Optional: Increase upload size limits for images
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB