spring.application.name=meenakshi

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_KEY}
cloudinary.api-secret=${CLOUDINARY_SECRET}

# Optional: Increase upload size limits for images
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG

# Set session timeout (in minutes)
server.servlet.session.timeout=5m

